### PR TITLE
Feat:button component Added

### PR DESCRIPTION
**Pull request by neetukumari4858**
Feat:button component Added
There are 4 types of buttons.

Primary button
Button with icon
Floating button.
Button with a link.
Please review the code

### CODE REVIEW

**Comment by krishnakant01** [comment]
looks good to merge

**Review by krishnakant01 — APPROVED** [review]

**Comment by krishnakant01** [comment]
some suggestions: define colors separately and use variables, name your buttons better (not btn1,2,3) try to name them as primary/secondary.

**Comment by neetukumari4858** [comment]
> some suggestions: define colors separately and use variables, name your buttons better (not btn1,2,3) try to name them as primary/secondary.

okey Thx.

**Review by kotalwar-krishna — APPROVED** [review]
same sagession what krishnakant give you. otherwise all good

**Pull request merged**
